-d C:\Users\tianr\Documents\9k_uart_loopback\impl\gwsynthesis\9k_uart_loopback.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\tianr\Documents\9k_uart_loopback\src\uart_loopback.cst
-cfg C:\Users\tianr\Documents\9k_uart_loopback\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
